//! `WmMcpServer` — the per-session MCP handler. Holds an
//! `Arc<AppState>` so each tool can reach auth, the registry, the
//! journal, etc. The router (`tool_router` field) is the registry of
//! all tools available on this server; rmcp's macros wire it up.
//!
//! Tools live under [`super::tools`] grouped by domain; each is
//! attached to this struct's `tool_router` via the `#[tool_router]`
//! attribute on a per-domain `impl` block.

use std::sync::Arc;

use rmcp::ServerHandler;
use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::tool_handler;

use crate::AppState;

// Suppress unused-imports lint: the `tool_router` static methods are
// generated by the `#[tool_router(router = <name>)]` macros applied
// in submodules. Without something pulling them in, the compiler
// can't see them — referencing them in `new()` above is enough.
#[allow(unused_imports)]
use super::tools;

#[derive(Clone)]
pub struct WmMcpServer {
    // Read by tool handlers added in task #70; the scaffold compiles
    // without them so we silence the lint until the first tool lands.
    #[allow(dead_code)]
    pub(super) state: Arc<AppState>,
    pub(super) tool_router: ToolRouter<Self>,
}

impl WmMcpServer {
    pub fn new(state: Arc<AppState>) -> Self {
        let tool_router = Self::identity_router()
            + Self::discovery_router()
            + Self::groups_router()
            + Self::routes_router()
            + Self::state_router()
            + Self::streaming_router();
        Self { state, tool_router }
    }
}

#[tool_handler(router = self.tool_router)]
impl ServerHandler for WmMcpServer {}
