//! `WmMcpServer` — the per-session MCP handler. Holds an
//! `Arc<AppState>` so each tool can reach auth, the registry, the
//! journal, etc. The router (`tool_router` field) is the registry of
//! all tools available on this server; rmcp's macros wire it up.
//!
//! Tools live under [`super::tools`] grouped by domain; each is
//! attached to this struct's `tool_router` via the `#[tool_router]`
//! attribute on a per-domain `impl` block.

use std::sync::Arc;

use rmcp::ServerHandler;
use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::tool_handler;
use tracing::Instrument;

use crate::AppState;

// Suppress unused-imports lint: the `tool_router` static methods are
// generated by the `#[tool_router(router = <name>)]` macros applied
// in submodules. Without something pulling them in, the compiler
// can't see them — referencing them in `new()` above is enough.
#[allow(unused_imports)]
use super::tools;

#[derive(Clone)]
pub struct WmMcpServer {
    // Read by tool handlers added in task #70; the scaffold compiles
    // without them so we silence the lint until the first tool lands.
    #[allow(dead_code)]
    pub(super) state: Arc<AppState>,
    pub(super) tool_router: ToolRouter<Self>,
}

impl WmMcpServer {
    pub fn new(state: Arc<AppState>) -> Self {
        let tool_router = Self::identity_router()
            + Self::capabilities_router()
            + Self::discovery_router()
            + Self::groups_router()
            + Self::routes_router()
            + Self::state_router()
            + Self::streaming_router();
        Self { state, tool_router }
    }
}

// `#[tool_handler]` generates `call_tool` ONLY if the impl doesn't
// already define one (it checks `has_method("call_tool", ...)`). We
// define our own so every tool invocation gets a `mcp.tool` span and a
// `wm.mcp.tool.*` metric, then hand off to the exact dispatch the macro
// would have used (`tool_router.call(tcc)`). list_tools / get_tool /
// get_info are still macro-generated.
#[tool_handler(router = self.tool_router)]
impl ServerHandler for WmMcpServer {
    async fn call_tool(
        &self,
        request: rmcp::model::CallToolRequestParams,
        context: rmcp::service::RequestContext<rmcp::RoleServer>,
    ) -> Result<rmcp::model::CallToolResponse, rmcp::ErrorData> {
        // The router IS the cardinality allowlist: a name it routes is a
        // registered tool (bounded set). An unrecognized name (client
        // typo / probing) collapses to "unknown" so the metric/span label
        // space can't be inflated by callers. ADR-0024.
        let tool = if self.tool_router.has_route(request.name.as_ref()) {
            request.name.to_string()
        } else {
            "unknown".to_string()
        };

        let span = tracing::info_span!("mcp.tool", "wm.mcp.tool" = tool.as_str());
        let started = std::time::Instant::now();
        let tcc = rmcp::handler::server::tool::ToolCallContext::new(self, request, context);
        let result = self.tool_router.call(tcc).instrument(span).await;
        let outcome = if result.is_ok() { "ok" } else { "error" };
        crate::metrics::record_mcp_tool(&tool, outcome, started.elapsed().as_millis() as u64);
        result
    }
}
