//! MCP-client OAuth Authorization Server — ADR-0019.
//!
//! WireMirage acts as its own OAuth 2.1 Authorization Server scoped to
//! the `/__api/mcp` resource so native MCP clients (Claude Desktop,
//! Cursor's MCP integration, the MCP Inspector) can authenticate
//! interactive users via the spec's authorization-code-with-PKCE flow.
//!
//! Slice 51 lands the foundation: discovery endpoints (RFC 9728 +
//! RFC 8414) and the four Valkey keyspaces the flow will use. No
//! flow endpoints yet — those come in slice 52.
//!
//! Storage layout (all under the admin bucket):
//!
//! * `oauth:client:{client_id}` — hash; one record per registered
//!   client. Holds the hashed `client_secret`, the registered
//!   redirect URIs, the OAuth metadata (grant_types, response_types,
//!   token_endpoint_auth_method), and lifecycle timestamps.
//! * `oauth:pending:{state}` — hash; bridges the authorize endpoint
//!   to the consent UI. 10-minute TTL. Holds client_id, redirect_uri,
//!   code_challenge, scope, and the client's original `state`
//!   parameter that we echo back on success.
//! * `oauth:code:{code}` — hash; issued authorization code awaiting
//!   token exchange. 10-minute TTL. Marked one-shot via `used_at`.
//! * `oauth:refresh:{token_hash}` — hash; refresh-token record, also
//!   one-shot (rotated on every exchange). 30-day TTL.
//!
//! Each helper here lives behind a `MutBucket` borrow so callers
//! can run multi-write sequences atomically (well, atomically per
//! storage operation — the in-memory backend and Valkey both treat
//! each write independently, which is fine for our shapes).

use axum::Json;
use axum::Router;
use axum::extract::State;
use axum::http::{HeaderMap, header};
use axum::routing::get;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::json;
use thiserror::Error;

use crate::AppState;
use crate::store::{Bucket, StoreError};

/// `pending_oauth_authorization` TTL — covers the user's round-trip
/// through the consent page. 10 minutes matches RFC 6749's
/// recommended ceiling on authorization-code lifetimes.
pub const PENDING_AUTH_TTL_SECONDS: u64 = 600;

/// `oauth_authorization_code` TTL. Same 10-minute ceiling.
pub const AUTH_CODE_TTL_SECONDS: u64 = 600;

/// Default access-token lifetime when we mint via the token endpoint
/// in slice 52. Surfaced here so the discovery endpoint can advertise
/// a coherent number ahead of time.
pub const ACCESS_TOKEN_TTL_SECONDS: u64 = 3600;

/// Refresh-token lifetime. 30 days matches the Arkiv reference impl
/// and the OAuth-spec recommended ceiling for long-lived sessions.
pub const REFRESH_TOKEN_TTL_SECONDS: u64 = 30 * 24 * 3600;

#[derive(Debug, Error)]
pub enum OAuthStoreError {
    #[error("storage backend error: {0}")]
    Storage(#[from] StoreError),
    #[error("malformed oauth record: {0}")]
    Malformed(String),
    #[error("oauth record not found")]
    NotFound,
}

/// One DCR-registered client (RFC 7591). The numeric `client_id` is
/// generated by us when the client registers; the secret hash is
/// argon2id-hashed at the same time and never stored in plaintext.
///
/// `redirect_uris` is the operator-authorized list — exact-match on
/// validation, except for `http://127.0.0.1:*` and `http://[::1]:*`
/// loopback patterns where the port is wildcarded (RFC 8252).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct OAuthClient {
    pub client_id: String,
    pub client_secret_hash: String,
    pub client_name: String,
    pub redirect_uris: Vec<String>,
    pub grant_types: Vec<String>,
    pub response_types: Vec<String>,
    /// "client_secret_post" or "client_secret_basic". Set at
    /// registration time; the token endpoint enforces it.
    pub token_endpoint_auth_method: String,
    pub created_at: DateTime<Utc>,
    pub last_used_at: Option<DateTime<Utc>>,
    pub revoked_at: Option<DateTime<Utc>>,
}

/// Authorize → consent bridge record. Keyed by the internal `state`
/// nonce we generate at /authorize time; consent page consumes it on
/// approve/deny.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct PendingAuthorization {
    pub client_id: String,
    pub redirect_uri: String,
    pub code_challenge: String,
    pub code_challenge_method: String,
    pub scope: String,
    /// The client's `state` parameter (NOT our internal nonce). We
    /// echo this back to the client on the final redirect so it can
    /// match its own request/response pair.
    pub original_state: Option<String>,
    pub created_at: DateTime<Utc>,
}

/// An issued authorization code awaiting `authorization_code` grant
/// exchange. Created when the user approves on the consent page.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct AuthorizationCode {
    pub code: String,
    pub client_id: String,
    pub user_id: String,
    pub redirect_uri: String,
    pub scope: String,
    pub code_challenge: String,
    pub code_challenge_method: String,
    pub created_at: DateTime<Utc>,
    /// Set on first successful exchange. The store helper refuses
    /// to load a code with `used_at` set.
    pub used_at: Option<DateTime<Utc>>,
}

/// A refresh token. Tokens themselves are random 48-byte values
/// URL-safe-base64 encoded; only their SHA-256 hash is persisted.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct RefreshToken {
    pub token_hash: String,
    pub client_id: String,
    pub user_id: String,
    pub scope: String,
    pub created_at: DateTime<Utc>,
    pub used_at: Option<DateTime<Utc>>,
    pub revoked_at: Option<DateTime<Utc>>,
}

// -- Client CRUD --------------------------------------------------------------

pub fn save_client(bucket: &mut Bucket, client: &OAuthClient) -> Result<(), OAuthStoreError> {
    let key = client_key(&client.client_id);
    write_json_hash(bucket, &key, client)?;
    Ok(())
}

pub fn load_client(
    bucket: &mut Bucket,
    client_id: &str,
) -> Result<Option<OAuthClient>, OAuthStoreError> {
    read_json_hash(bucket, &client_key(client_id))
}

/// Mark a client revoked. Future authorize requests for this
/// client_id reject with `unauthorized_client`. Existing access
/// tokens stay valid until they expire; existing refresh tokens
/// stop working on next rotation.
pub fn revoke_client(bucket: &mut Bucket, client_id: &str) -> Result<bool, OAuthStoreError> {
    let key = client_key(client_id);
    let Some(mut client): Option<OAuthClient> = read_json_hash(bucket, &key)? else {
        return Ok(false);
    };
    if client.revoked_at.is_some() {
        return Ok(false);
    }
    client.revoked_at = Some(Utc::now());
    write_json_hash(bucket, &key, &client)?;
    Ok(true)
}

// -- Pending authorization ----------------------------------------------------

pub fn save_pending(
    bucket: &mut Bucket,
    state: &str,
    pending: &PendingAuthorization,
) -> Result<(), OAuthStoreError> {
    let key = pending_key(state);
    write_json_hash(bucket, &key, pending)?;
    bucket.set_ttl(&key, PENDING_AUTH_TTL_SECONDS)?;
    Ok(())
}

/// One-shot read: returns the pending authorization and deletes the
/// record in the same call. The TTL is the safety net; this is the
/// happy path's cleanup.
pub fn consume_pending(
    bucket: &mut Bucket,
    state: &str,
) -> Result<Option<PendingAuthorization>, OAuthStoreError> {
    let key = pending_key(state);
    let pending = read_json_hash(bucket, &key)?;
    if pending.is_some() {
        bucket.delete(&key)?;
    }
    Ok(pending)
}

// -- Authorization code -------------------------------------------------------

pub fn save_authorization_code(
    bucket: &mut Bucket,
    code: &AuthorizationCode,
) -> Result<(), OAuthStoreError> {
    let key = code_key(&code.code);
    write_json_hash(bucket, &key, code)?;
    bucket.set_ttl(&key, AUTH_CODE_TTL_SECONDS)?;
    Ok(())
}

/// Look up the code without marking it used. The exchange endpoint
/// uses this to validate the PKCE verifier before committing.
pub fn load_authorization_code(
    bucket: &mut Bucket,
    code: &str,
) -> Result<Option<AuthorizationCode>, OAuthStoreError> {
    read_json_hash(bucket, &code_key(code))
}

/// Atomically mark a code consumed. Returns the loaded record on
/// success; `Ok(None)` if the code never existed; `Ok(Some(...))`
/// with `used_at == Some(_)` if it was already consumed (caller
/// rejects).
pub fn consume_authorization_code(
    bucket: &mut Bucket,
    code: &str,
) -> Result<Option<AuthorizationCode>, OAuthStoreError> {
    let key = code_key(code);
    let Some(mut record): Option<AuthorizationCode> = read_json_hash(bucket, &key)? else {
        return Ok(None);
    };
    if record.used_at.is_some() {
        return Ok(Some(record));
    }
    record.used_at = Some(Utc::now());
    write_json_hash(bucket, &key, &record)?;
    Ok(Some(record))
}

// -- Refresh token ------------------------------------------------------------

pub fn save_refresh_token(
    bucket: &mut Bucket,
    token: &RefreshToken,
) -> Result<(), OAuthStoreError> {
    let key = refresh_key(&token.token_hash);
    write_json_hash(bucket, &key, token)?;
    bucket.set_ttl(&key, REFRESH_TOKEN_TTL_SECONDS)?;
    Ok(())
}

pub fn load_refresh_token(
    bucket: &mut Bucket,
    token_hash: &str,
) -> Result<Option<RefreshToken>, OAuthStoreError> {
    read_json_hash(bucket, &refresh_key(token_hash))
}

/// Rotate a refresh token: mark the old one consumed and prepare to
/// write a new one. Caller writes the new record via
/// `save_refresh_token` after this returns. If the loaded record is
/// already used or revoked, returns it with the existing markers so
/// the caller can reject.
pub fn consume_refresh_token(
    bucket: &mut Bucket,
    token_hash: &str,
) -> Result<Option<RefreshToken>, OAuthStoreError> {
    let key = refresh_key(token_hash);
    let Some(mut record): Option<RefreshToken> = read_json_hash(bucket, &key)? else {
        return Ok(None);
    };
    if record.used_at.is_some() || record.revoked_at.is_some() {
        return Ok(Some(record));
    }
    record.used_at = Some(Utc::now());
    write_json_hash(bucket, &key, &record)?;
    Ok(Some(record))
}

// -- Discovery endpoints (RFC 9728 + RFC 8414) -------------------------------
//
// These are served unauthenticated under `/.well-known/*` so any MCP
// client can ask "where do I auth against this resource?" without
// holding a token yet. Both endpoints return JSON shaped per the
// respective RFC; the URLs embedded in the response are derived from
// the request's Host header (and X-Forwarded-Proto when the operator
// trusts it) so deployments behind a TLS edge advertise the public
// URL rather than the loopback the host listens on.

/// MCP-OAuth discovery router. Mounted at the root from
/// `server::router()` so the well-known paths land as
/// `https://host/.well-known/...`.
pub fn router() -> Router<AppState> {
    Router::new()
        .route(
            "/.well-known/oauth-protected-resource",
            get(protected_resource_metadata),
        )
        .route(
            "/.well-known/oauth-authorization-server",
            get(authorization_server_metadata),
        )
}

/// RFC 9728 — Protected Resource Metadata. Names the AS and the
/// resource URL. Clients hitting `/__api/mcp` without a valid token
/// will (per slice D) get a `WWW-Authenticate: Bearer
/// resource_metadata="..."` header pointing at this URL.
async fn protected_resource_metadata(
    State(state): State<AppState>,
    headers: HeaderMap,
) -> Json<serde_json::Value> {
    let base = derive_public_base(&headers, state.trust_forwarded_headers());
    Json(json!({
        "resource": format!("{base}/__api/mcp"),
        "authorization_servers": [base.clone()],
        "scopes_supported": ["*"],
        "bearer_methods_supported": ["header"],
    }))
}

/// RFC 8414 — Authorization Server Metadata. Names every endpoint a
/// client needs to drive the OAuth 2.1 + PKCE flow. The endpoints
/// themselves are not yet live in slice 51 (they land in slice 52),
/// but advertising them now lets clients run discovery and surface
/// "endpoint not implemented" errors instead of "metadata missing"
/// errors when they probe.
async fn authorization_server_metadata(
    State(state): State<AppState>,
    headers: HeaderMap,
) -> Json<serde_json::Value> {
    let base = derive_public_base(&headers, state.trust_forwarded_headers());
    Json(json!({
        "issuer": base.clone(),
        "authorization_endpoint": format!("{base}/__auth/oauth/authorize"),
        "token_endpoint": format!("{base}/__auth/oauth/token"),
        "registration_endpoint": format!("{base}/__auth/oauth/register"),
        "revocation_endpoint": format!("{base}/__auth/oauth/revoke"),
        "scopes_supported": ["*"],
        "response_types_supported": ["code"],
        "grant_types_supported": ["authorization_code", "refresh_token"],
        "code_challenge_methods_supported": ["S256"],
        "token_endpoint_auth_methods_supported": [
            "client_secret_post",
            "client_secret_basic",
        ],
        "revocation_endpoint_auth_methods_supported": [
            "client_secret_post",
            "client_secret_basic",
        ],
    }))
}

/// Build the base URL (`scheme://host`) for advertising discovery
/// values. Mirrors the redirect-URI logic in `auth_api.rs`: derive
/// from the `Host` header (always present on HTTP/1.1), and honor
/// `X-Forwarded-Proto` only when `WM_TRUST_FORWARDED_HEADERS=1` so
/// a directly-reachable host can't be tricked into advertising
/// HTTPS URLs it can't actually serve.
fn derive_public_base(headers: &HeaderMap, trust_forwarded: bool) -> String {
    let host = headers
        .get(header::HOST)
        .and_then(|v| v.to_str().ok())
        .unwrap_or("localhost:8080");
    let scheme = if trust_forwarded
        && let Some(v) = headers.get("x-forwarded-proto")
        && let Ok(s) = v.to_str()
        && !s.is_empty()
    {
        s.to_string()
    } else {
        "http".to_string()
    };
    format!("{scheme}://{host}")
}

// -- Key helpers --------------------------------------------------------------

fn client_key(client_id: &str) -> String {
    format!("oauth:client:{client_id}")
}

fn pending_key(state: &str) -> String {
    format!("oauth:pending:{state}")
}

fn code_key(code: &str) -> String {
    format!("oauth:code:{code}")
}

fn refresh_key(hash: &str) -> String {
    format!("oauth:refresh:{hash}")
}

// -- Hash-of-JSON encoding ---------------------------------------------------
//
// The existing wm_host storage layer is byte-keyed-and-valued — no
// native struct support. Most other records (Token, GroupRecord)
// fan out one hash field per attribute, which costs a method call
// per field. OAuth records are short-lived and only ever round-tripped
// as a whole, so we serialize the entire struct to JSON and stash it
// in a single hash field (`data`). Cuts the wire-protocol roundtrip
// count from N to 1 per record without losing typability.

fn write_json_hash<T: Serialize>(
    bucket: &mut Bucket,
    key: &str,
    value: &T,
) -> Result<(), OAuthStoreError> {
    let bytes = serde_json::to_vec(value)
        .map_err(|e| OAuthStoreError::Malformed(format!("encode JSON: {e}")))?;
    bucket.hash_set(key, "data", bytes)?;
    Ok(())
}

fn read_json_hash<T: serde::de::DeserializeOwned>(
    bucket: &mut Bucket,
    key: &str,
) -> Result<Option<T>, OAuthStoreError> {
    let Some(bytes) = bucket.hash_get(key, "data")? else {
        return Ok(None);
    };
    let value = serde_json::from_slice(&bytes)
        .map_err(|e| OAuthStoreError::Malformed(format!("decode JSON: {e}")))?;
    Ok(Some(value))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::store::Storage;

    fn fresh_bucket() -> Bucket {
        Storage::in_memory().admin_bucket().expect("bucket")
    }

    fn sample_client() -> OAuthClient {
        OAuthClient {
            client_id: "cli_abc".into(),
            client_secret_hash: "argon2id$...".into(),
            client_name: "Claude Desktop".into(),
            redirect_uris: vec!["http://127.0.0.1:0/callback".into()],
            grant_types: vec!["authorization_code".into(), "refresh_token".into()],
            response_types: vec!["code".into()],
            token_endpoint_auth_method: "client_secret_post".into(),
            created_at: Utc::now(),
            last_used_at: None,
            revoked_at: None,
        }
    }

    #[test]
    fn client_round_trips_through_storage() {
        let mut b = fresh_bucket();
        let c = sample_client();
        save_client(&mut b, &c).unwrap();
        let loaded = load_client(&mut b, &c.client_id).unwrap().unwrap();
        assert_eq!(loaded, c);
    }

    #[test]
    fn load_client_missing_returns_none() {
        let mut b = fresh_bucket();
        assert!(load_client(&mut b, "nope").unwrap().is_none());
    }

    #[test]
    fn revoke_client_marks_revoked_at() {
        let mut b = fresh_bucket();
        let c = sample_client();
        save_client(&mut b, &c).unwrap();
        assert!(revoke_client(&mut b, &c.client_id).unwrap());
        let loaded = load_client(&mut b, &c.client_id).unwrap().unwrap();
        assert!(loaded.revoked_at.is_some());
        // Already-revoked: second call is a no-op (returns false).
        assert!(!revoke_client(&mut b, &c.client_id).unwrap());
    }

    #[test]
    fn revoke_client_unknown_returns_false() {
        let mut b = fresh_bucket();
        assert!(!revoke_client(&mut b, "nope").unwrap());
    }

    #[test]
    fn pending_authorization_round_trip_and_consume() {
        let mut b = fresh_bucket();
        let p = PendingAuthorization {
            client_id: "cli_abc".into(),
            redirect_uri: "http://127.0.0.1:0/cb".into(),
            code_challenge: "challenge".into(),
            code_challenge_method: "S256".into(),
            scope: "*".into(),
            original_state: Some("client-state-xyz".into()),
            created_at: Utc::now(),
        };
        save_pending(&mut b, "internal-state", &p).unwrap();

        // First consume returns the record and deletes it.
        let first = consume_pending(&mut b, "internal-state").unwrap();
        assert_eq!(first, Some(p));
        // Second consume returns None.
        assert!(consume_pending(&mut b, "internal-state").unwrap().is_none());
    }

    #[test]
    fn authorization_code_consume_is_one_shot() {
        let mut b = fresh_bucket();
        let c = AuthorizationCode {
            code: "code_xyz".into(),
            client_id: "cli_abc".into(),
            user_id: "01HUSER".into(),
            redirect_uri: "http://127.0.0.1:0/cb".into(),
            scope: "*".into(),
            code_challenge: "ch".into(),
            code_challenge_method: "S256".into(),
            created_at: Utc::now(),
            used_at: None,
        };
        save_authorization_code(&mut b, &c).unwrap();

        // First consume marks used_at and returns the (now-marked) record.
        let first = consume_authorization_code(&mut b, "code_xyz")
            .unwrap()
            .unwrap();
        assert!(first.used_at.is_some());

        // Second consume returns the SAME record (still marked) so the
        // caller can distinguish "expired / never existed" (None) from
        // "already used" (Some with used_at set, which the token
        // endpoint rejects with `invalid_grant`).
        let second = consume_authorization_code(&mut b, "code_xyz")
            .unwrap()
            .unwrap();
        assert!(second.used_at.is_some());
        assert_eq!(second.code, "code_xyz");

        // Truly missing → None.
        assert!(
            consume_authorization_code(&mut b, "nope")
                .unwrap()
                .is_none()
        );
    }

    #[test]
    fn refresh_token_rotation_marks_used() {
        let mut b = fresh_bucket();
        let t = RefreshToken {
            token_hash: "hash1".into(),
            client_id: "cli_abc".into(),
            user_id: "01HUSER".into(),
            scope: "*".into(),
            created_at: Utc::now(),
            used_at: None,
            revoked_at: None,
        };
        save_refresh_token(&mut b, &t).unwrap();

        let first = consume_refresh_token(&mut b, "hash1").unwrap().unwrap();
        assert!(first.used_at.is_some());

        // Second consume sees used_at and bounces.
        let second = consume_refresh_token(&mut b, "hash1").unwrap().unwrap();
        assert!(second.used_at.is_some());
    }

    #[test]
    fn refresh_token_revoked_bounces() {
        let mut b = fresh_bucket();
        let t = RefreshToken {
            token_hash: "hash2".into(),
            client_id: "cli_abc".into(),
            user_id: "01HUSER".into(),
            scope: "*".into(),
            created_at: Utc::now(),
            used_at: None,
            revoked_at: Some(Utc::now()),
        };
        save_refresh_token(&mut b, &t).unwrap();
        let loaded = consume_refresh_token(&mut b, "hash2").unwrap().unwrap();
        assert!(loaded.revoked_at.is_some());
        // used_at stays None — we don't mark a revoked token as used,
        // it just stays revoked.
        assert!(loaded.used_at.is_none());
    }
}
