//! MCP-client OAuth Authorization Server — ADR-0019.
//!
//! WireMirage acts as its own OAuth 2.1 Authorization Server scoped to
//! the `/__api/mcp` resource so native MCP clients (Claude Desktop,
//! Cursor's MCP integration, the MCP Inspector) can authenticate
//! interactive users via the spec's authorization-code-with-PKCE flow.
//!
//! Slice 51 lands the foundation: discovery endpoints (RFC 9728 +
//! RFC 8414) and the four Valkey keyspaces the flow will use. No
//! flow endpoints yet — those come in slice 52.
//!
//! Storage layout (all under the admin bucket):
//!
//! * `oauth:client:{client_id}` — hash; one record per registered
//!   client. Holds the hashed `client_secret`, the registered
//!   redirect URIs, the OAuth metadata (grant_types, response_types,
//!   token_endpoint_auth_method), and lifecycle timestamps.
//! * `oauth:pending:{state}` — hash; bridges the authorize endpoint
//!   to the consent UI. 10-minute TTL. Holds client_id, redirect_uri,
//!   code_challenge, scope, and the client's original `state`
//!   parameter that we echo back on success.
//! * `oauth:code:{code}` — hash; issued authorization code awaiting
//!   token exchange. 10-minute TTL. Marked one-shot via `used_at`.
//! * `oauth:refresh:{token_hash}` — hash; refresh-token record, also
//!   one-shot (rotated on every exchange). 30-day TTL.
//!
//! Each helper here lives behind a `MutBucket` borrow so callers
//! can run multi-write sequences atomically (well, atomically per
//! storage operation — the in-memory backend and Valkey both treat
//! each write independently, which is fine for our shapes).

use std::collections::HashMap;

use axum::Form;
use axum::Json;
use axum::Router;
use axum::extract::{Query, State};
use axum::http::{HeaderMap, StatusCode, header};
use axum::response::{IntoResponse, Redirect, Response};
use axum::routing::{get, post};
use base64::Engine as _;
use base64::engine::general_purpose::URL_SAFE_NO_PAD as B64URL;
use chrono::{DateTime, Utc};
use minijinja::context;
use rand::RngCore;
use serde::{Deserialize, Serialize};
use serde_json::json;
use sha2::{Digest, Sha256};
use thiserror::Error;

use crate::AppState;
use crate::store::{Bucket, StoreError};

/// `pending_oauth_authorization` TTL — covers the user's round-trip
/// through the consent page. 10 minutes matches RFC 6749's
/// recommended ceiling on authorization-code lifetimes.
pub const PENDING_AUTH_TTL_SECONDS: u64 = 600;

/// `oauth_authorization_code` TTL. Same 10-minute ceiling.
pub const AUTH_CODE_TTL_SECONDS: u64 = 600;

/// Default access-token lifetime when we mint via the token endpoint
/// in slice 52. Surfaced here so the discovery endpoint can advertise
/// a coherent number ahead of time.
pub const ACCESS_TOKEN_TTL_SECONDS: u64 = 3600;

/// Refresh-token lifetime. 30 days matches the Arkiv reference impl
/// and the OAuth-spec recommended ceiling for long-lived sessions.
pub const REFRESH_TOKEN_TTL_SECONDS: u64 = 30 * 24 * 3600;

#[derive(Debug, Error)]
pub enum OAuthStoreError {
    #[error("storage backend error: {0}")]
    Storage(#[from] StoreError),
    #[error("malformed oauth record: {0}")]
    Malformed(String),
    #[error("oauth record not found")]
    NotFound,
}

/// One DCR-registered client (RFC 7591). The numeric `client_id` is
/// generated by us when the client registers; the secret hash is
/// argon2id-hashed at the same time and never stored in plaintext.
///
/// `redirect_uris` is the operator-authorized list — exact-match on
/// validation, except for `http://127.0.0.1:*` and `http://[::1]:*`
/// loopback patterns where the port is wildcarded (RFC 8252).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct OAuthClient {
    pub client_id: String,
    pub client_secret_hash: String,
    pub client_name: String,
    pub redirect_uris: Vec<String>,
    pub grant_types: Vec<String>,
    pub response_types: Vec<String>,
    /// "client_secret_post" or "client_secret_basic". Set at
    /// registration time; the token endpoint enforces it.
    pub token_endpoint_auth_method: String,
    pub created_at: DateTime<Utc>,
    pub last_used_at: Option<DateTime<Utc>>,
    pub revoked_at: Option<DateTime<Utc>>,
}

/// Authorize → consent bridge record. Keyed by the internal `state`
/// nonce we generate at /authorize time; consent page consumes it on
/// approve/deny.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct PendingAuthorization {
    pub client_id: String,
    pub redirect_uri: String,
    pub code_challenge: String,
    pub code_challenge_method: String,
    pub scope: String,
    /// The client's `state` parameter (NOT our internal nonce). We
    /// echo this back to the client on the final redirect so it can
    /// match its own request/response pair.
    pub original_state: Option<String>,
    pub created_at: DateTime<Utc>,
}

/// An issued authorization code awaiting `authorization_code` grant
/// exchange. Created when the user approves on the consent page.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct AuthorizationCode {
    pub code: String,
    pub client_id: String,
    pub user_id: String,
    pub redirect_uri: String,
    pub scope: String,
    pub code_challenge: String,
    pub code_challenge_method: String,
    pub created_at: DateTime<Utc>,
    /// Set on first successful exchange. The store helper refuses
    /// to load a code with `used_at` set.
    pub used_at: Option<DateTime<Utc>>,
}

/// A refresh token. Tokens themselves are random 48-byte values
/// URL-safe-base64 encoded; only their SHA-256 hash is persisted.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct RefreshToken {
    pub token_hash: String,
    pub client_id: String,
    pub user_id: String,
    pub scope: String,
    pub created_at: DateTime<Utc>,
    pub used_at: Option<DateTime<Utc>>,
    pub revoked_at: Option<DateTime<Utc>>,
}

/// An issued access token (`wmm_<random>`). Only the hash is stored;
/// the plaintext lives in the client and on the auth header. Auth
/// extractor looks up by SHA-256 hash, the same shape as the existing
/// `wmt_` path. TTL on the Valkey key (1 hour by default) is the
/// source of truth for expiry.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct AccessToken {
    pub token_hash: String,
    pub client_id: String,
    pub user_id: String,
    pub scope: String,
    pub created_at: DateTime<Utc>,
    pub expires_at: DateTime<Utc>,
}

// -- Client CRUD --------------------------------------------------------------

pub fn save_client(bucket: &mut Bucket, client: &OAuthClient) -> Result<(), OAuthStoreError> {
    let key = client_key(&client.client_id);
    write_json_hash(bucket, &key, client)?;
    Ok(())
}

pub fn load_client(
    bucket: &mut Bucket,
    client_id: &str,
) -> Result<Option<OAuthClient>, OAuthStoreError> {
    read_json_hash(bucket, &client_key(client_id))
}

/// Mark a client revoked. Future authorize requests for this
/// client_id reject with `unauthorized_client`. Existing access
/// tokens stay valid until they expire; existing refresh tokens
/// stop working on next rotation.
pub fn revoke_client(bucket: &mut Bucket, client_id: &str) -> Result<bool, OAuthStoreError> {
    let key = client_key(client_id);
    let Some(mut client): Option<OAuthClient> = read_json_hash(bucket, &key)? else {
        return Ok(false);
    };
    if client.revoked_at.is_some() {
        return Ok(false);
    }
    client.revoked_at = Some(Utc::now());
    write_json_hash(bucket, &key, &client)?;
    Ok(true)
}

// -- Pending authorization ----------------------------------------------------

pub fn save_pending(
    bucket: &mut Bucket,
    state: &str,
    pending: &PendingAuthorization,
) -> Result<(), OAuthStoreError> {
    let key = pending_key(state);
    write_json_hash(bucket, &key, pending)?;
    bucket.set_ttl(&key, PENDING_AUTH_TTL_SECONDS)?;
    Ok(())
}

/// One-shot read: returns the pending authorization and deletes the
/// record in the same call. The TTL is the safety net; this is the
/// happy path's cleanup.
pub fn consume_pending(
    bucket: &mut Bucket,
    state: &str,
) -> Result<Option<PendingAuthorization>, OAuthStoreError> {
    let key = pending_key(state);
    let pending = read_json_hash(bucket, &key)?;
    if pending.is_some() {
        bucket.delete(&key)?;
    }
    Ok(pending)
}

// -- Authorization code -------------------------------------------------------

pub fn save_authorization_code(
    bucket: &mut Bucket,
    code: &AuthorizationCode,
) -> Result<(), OAuthStoreError> {
    let key = code_key(&code.code);
    write_json_hash(bucket, &key, code)?;
    bucket.set_ttl(&key, AUTH_CODE_TTL_SECONDS)?;
    Ok(())
}

/// Look up the code without marking it used. The exchange endpoint
/// uses this to validate the PKCE verifier before committing.
pub fn load_authorization_code(
    bucket: &mut Bucket,
    code: &str,
) -> Result<Option<AuthorizationCode>, OAuthStoreError> {
    read_json_hash(bucket, &code_key(code))
}

/// Atomically mark a code consumed. Returns `Some(record)` on the
/// FIRST consume; `None` on replay or when the code never existed —
/// both shapes are rejection cases from the token endpoint's point
/// of view, and collapsing them into one variant means callers can't
/// accidentally accept a replay.
pub fn consume_authorization_code(
    bucket: &mut Bucket,
    code: &str,
) -> Result<Option<AuthorizationCode>, OAuthStoreError> {
    let key = code_key(code);
    let Some(mut record): Option<AuthorizationCode> = read_json_hash(bucket, &key)? else {
        return Ok(None);
    };
    if record.used_at.is_some() {
        return Ok(None);
    }
    record.used_at = Some(Utc::now());
    write_json_hash(bucket, &key, &record)?;
    Ok(Some(record))
}

// -- Refresh token ------------------------------------------------------------

pub fn save_refresh_token(
    bucket: &mut Bucket,
    token: &RefreshToken,
) -> Result<(), OAuthStoreError> {
    let key = refresh_key(&token.token_hash);
    write_json_hash(bucket, &key, token)?;
    bucket.set_ttl(&key, REFRESH_TOKEN_TTL_SECONDS)?;
    // Per-user index so the tokens page can enumerate active grants
    // without scanning every refresh-token record in the host. The
    // index accumulates hashes (rotation adds, revoke marks the
    // record but doesn't delete from the index); list_*_by_user
    // filters on used_at/revoked_at at read time. Stale entries cost
    // a small per-read overhead and a Valkey hash lookup — fine for
    // the per-user-per-client volume we're aiming for.
    bucket.set_add(&refresh_user_index_key(&token.user_id), &token.token_hash)?;
    Ok(())
}

pub fn load_refresh_token(
    bucket: &mut Bucket,
    token_hash: &str,
) -> Result<Option<RefreshToken>, OAuthStoreError> {
    read_json_hash(bucket, &refresh_key(token_hash))
}

/// Rotate a refresh token: mark the old one consumed and load it.
/// Returns `Some(record)` only on the FIRST consume of an unused,
/// unrevoked token. Returns `None` for missing / already-used /
/// revoked — handler maps any of those to `invalid_grant`. (Revoked
/// is distinguished separately via `load_refresh_token` when the
/// caller wants to log differently.)
pub fn consume_refresh_token(
    bucket: &mut Bucket,
    token_hash: &str,
) -> Result<Option<RefreshToken>, OAuthStoreError> {
    let key = refresh_key(token_hash);
    let Some(mut record): Option<RefreshToken> = read_json_hash(bucket, &key)? else {
        return Ok(None);
    };
    if record.used_at.is_some() || record.revoked_at.is_some() {
        return Ok(None);
    }
    record.used_at = Some(Utc::now());
    write_json_hash(bucket, &key, &record)?;
    Ok(Some(record))
}

// -- Discovery endpoints (RFC 9728 + RFC 8414) -------------------------------
//
// These are served unauthenticated under `/.well-known/*` so any MCP
// client can ask "where do I auth against this resource?" without
// holding a token yet. Both endpoints return JSON shaped per the
// respective RFC; the URLs embedded in the response are derived from
// the request's Host header (and X-Forwarded-Proto when the operator
// trusts it) so deployments behind a TLS edge advertise the public
// URL rather than the loopback the host listens on.

/// MCP-OAuth discovery + flow router. Mounted at the root from
/// `server::router()` so the well-known paths land as
/// `https://host/.well-known/...` and the flow endpoints as
/// `/__auth/oauth/...` / `/__ui/oauth/...`.
///
/// CSRF is layered onto the consent UI only — `/register` and
/// `/token` are called by external MCP clients and can't carry a
/// `_csrf` form field; their CSRF defence is the OAuth `state`
/// parameter plus `client_secret` authentication. `/authorize` is a
/// GET, so CSRF doesn't apply there either.
pub fn router(state: AppState) -> Router<AppState> {
    let public = Router::new()
        .route(
            "/.well-known/oauth-protected-resource",
            get(protected_resource_metadata),
        )
        .route(
            "/.well-known/oauth-authorization-server",
            get(authorization_server_metadata),
        )
        .route("/__auth/oauth/register", post(register))
        .route("/__auth/oauth/authorize", get(authorize))
        .route("/__auth/oauth/token", post(token))
        .route("/__auth/oauth/revoke", post(revoke));

    let consent = Router::new()
        .route(
            "/__ui/oauth/consent",
            get(consent_page).post(consent_submit),
        )
        .layer(axum::middleware::from_fn_with_state(
            state,
            crate::ui::csrf::csrf_middleware,
        ));

    public.merge(consent)
}

/// RFC 9728 — Protected Resource Metadata. Names the AS and the
/// resource URL. Clients hitting `/__api/mcp` without a valid token
/// will (per slice D) get a `WWW-Authenticate: Bearer
/// resource_metadata="..."` header pointing at this URL.
async fn protected_resource_metadata(
    State(state): State<AppState>,
    headers: HeaderMap,
) -> Json<serde_json::Value> {
    let base = derive_public_base(&headers, state.trust_forwarded_headers());
    Json(json!({
        "resource": format!("{base}/__api/mcp"),
        "authorization_servers": [base.clone()],
        "scopes_supported": ["*"],
        "bearer_methods_supported": ["header"],
    }))
}

/// RFC 8414 — Authorization Server Metadata. Names every endpoint a
/// client needs to drive the OAuth 2.1 + PKCE flow. The endpoints
/// themselves are not yet live in slice 51 (they land in slice 52),
/// but advertising them now lets clients run discovery and surface
/// "endpoint not implemented" errors instead of "metadata missing"
/// errors when they probe.
async fn authorization_server_metadata(
    State(state): State<AppState>,
    headers: HeaderMap,
) -> Json<serde_json::Value> {
    let base = derive_public_base(&headers, state.trust_forwarded_headers());
    Json(json!({
        "issuer": base.clone(),
        "authorization_endpoint": format!("{base}/__auth/oauth/authorize"),
        "token_endpoint": format!("{base}/__auth/oauth/token"),
        "registration_endpoint": format!("{base}/__auth/oauth/register"),
        "revocation_endpoint": format!("{base}/__auth/oauth/revoke"),
        "scopes_supported": ["*"],
        "response_types_supported": ["code"],
        "grant_types_supported": ["authorization_code", "refresh_token"],
        "code_challenge_methods_supported": ["S256"],
        "token_endpoint_auth_methods_supported": [
            "client_secret_post",
            "client_secret_basic",
        ],
        "revocation_endpoint_auth_methods_supported": [
            "client_secret_post",
            "client_secret_basic",
        ],
    }))
}

/// Build the base URL (`scheme://host`) for advertising discovery
/// values. Mirrors the redirect-URI logic in `auth_api.rs`: derive
/// from the `Host` header (always present on HTTP/1.1), and honor
/// `X-Forwarded-Proto` only when `WM_TRUST_FORWARDED_HEADERS=1` so
/// a directly-reachable host can't be tricked into advertising
/// HTTPS URLs it can't actually serve.
fn derive_public_base(headers: &HeaderMap, trust_forwarded: bool) -> String {
    let host = headers
        .get(header::HOST)
        .and_then(|v| v.to_str().ok())
        .unwrap_or("localhost:8080");
    let scheme = if trust_forwarded
        && let Some(v) = headers.get("x-forwarded-proto")
        && let Ok(s) = v.to_str()
        && !s.is_empty()
    {
        s.to_string()
    } else {
        "http".to_string()
    };
    format!("{scheme}://{host}")
}

// -- Access token CRUD --------------------------------------------------------

pub fn save_access_token(bucket: &mut Bucket, token: &AccessToken) -> Result<(), OAuthStoreError> {
    let key = access_key(&token.token_hash);
    write_json_hash(bucket, &key, token)?;
    // TTL aligns with `expires_at`. We compute it from the record so
    // a token written close to expiry still gets a sensible TTL.
    let ttl = (token.expires_at - Utc::now()).num_seconds().max(1) as u64;
    bucket.set_ttl(&key, ttl)?;
    Ok(())
}

pub fn load_access_token(
    bucket: &mut Bucket,
    token_hash: &str,
) -> Result<Option<AccessToken>, OAuthStoreError> {
    read_json_hash(bucket, &access_key(token_hash))
}

/// Delete an access token by hash (used by the revoke endpoint in
/// slice 53). The TTL would expire it anyway; this is for instant
/// revocation.
pub fn delete_access_token(bucket: &mut Bucket, token_hash: &str) -> Result<(), OAuthStoreError> {
    bucket.delete(&access_key(token_hash))?;
    Ok(())
}

// -- Per-user grant listing ---------------------------------------------------

/// A flattened summary of one (user, client) OAuth grant — what the
/// tokens page renders. Pulled together from a refresh-token record
/// plus the corresponding client record; deduplicated by client_id
/// at the call site so refresh-token rotation doesn't surface as
/// duplicate rows.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OAuthGrantSummary {
    pub client_id: String,
    pub client_name: String,
    pub scope: String,
    pub granted_at: DateTime<Utc>,
    pub expires_at: DateTime<Utc>,
}

/// List the user's active OAuth grants. Walks the per-user refresh-
/// token index, filters out used/revoked entries (rotation leaves
/// the old entry in the index but used_at gets set on it), looks up
/// the matching client record, and deduplicates by client_id —
/// returning the most recent grant per client.
pub fn list_active_oauth_grants(
    bucket: &mut Bucket,
    user_id: &str,
) -> Result<Vec<OAuthGrantSummary>, OAuthStoreError> {
    let hashes = bucket.set_members(&refresh_user_index_key(user_id))?;
    let ttl = chrono::Duration::seconds(REFRESH_TOKEN_TTL_SECONDS as i64);

    let mut by_client: std::collections::HashMap<String, OAuthGrantSummary> =
        std::collections::HashMap::new();

    for hash in hashes {
        let Some(refresh): Option<RefreshToken> = read_json_hash(bucket, &refresh_key(&hash))?
        else {
            continue;
        };
        if refresh.used_at.is_some() || refresh.revoked_at.is_some() {
            continue;
        }
        let Some(client) = load_client(bucket, &refresh.client_id)? else {
            continue;
        };
        let summary = OAuthGrantSummary {
            client_id: refresh.client_id.clone(),
            client_name: client.client_name,
            scope: refresh.scope.clone(),
            granted_at: refresh.created_at,
            expires_at: refresh.created_at + ttl,
        };
        by_client
            .entry(refresh.client_id)
            .and_modify(|existing| {
                if summary.granted_at > existing.granted_at {
                    *existing = summary.clone();
                }
            })
            .or_insert(summary);
    }

    let mut out: Vec<OAuthGrantSummary> = by_client.into_values().collect();
    out.sort_by_key(|g| std::cmp::Reverse(g.granted_at));
    Ok(out)
}

/// Revoke every refresh token the user has for `client_id`. Returns
/// the number of refresh tokens marked revoked. Access tokens are
/// not enumerated — their 1-hour TTL covers the post-revoke window,
/// and there's no per-user index on them today.
pub fn revoke_grants_for_client(
    bucket: &mut Bucket,
    user_id: &str,
    client_id: &str,
) -> Result<u32, OAuthStoreError> {
    let hashes = bucket.set_members(&refresh_user_index_key(user_id))?;
    let mut revoked = 0u32;
    for hash in hashes {
        let Some(mut refresh): Option<RefreshToken> = read_json_hash(bucket, &refresh_key(&hash))?
        else {
            continue;
        };
        if refresh.client_id != client_id {
            continue;
        }
        if refresh.revoked_at.is_some() {
            continue;
        }
        refresh.revoked_at = Some(Utc::now());
        save_refresh_token(bucket, &refresh)?;
        revoked += 1;
    }
    Ok(revoked)
}

// -- Key helpers --------------------------------------------------------------

fn client_key(client_id: &str) -> String {
    format!("oauth:client:{client_id}")
}

fn pending_key(state: &str) -> String {
    format!("oauth:pending:{state}")
}

fn code_key(code: &str) -> String {
    format!("oauth:code:{code}")
}

fn refresh_key(hash: &str) -> String {
    format!("oauth:refresh:{hash}")
}

fn refresh_user_index_key(user_id: &str) -> String {
    format!("oauth:refresh:by-user:{user_id}")
}

fn access_key(hash: &str) -> String {
    format!("oauth:access:{hash}")
}

// -- Hash-of-JSON encoding ---------------------------------------------------
//
// The existing wm_host storage layer is byte-keyed-and-valued — no
// native struct support. Most other records (Token, GroupRecord)
// fan out one hash field per attribute, which costs a method call
// per field. OAuth records are short-lived and only ever round-tripped
// as a whole, so we serialize the entire struct to JSON and stash it
// in a single hash field (`data`). Cuts the wire-protocol roundtrip
// count from N to 1 per record without losing typability.

fn write_json_hash<T: Serialize>(
    bucket: &mut Bucket,
    key: &str,
    value: &T,
) -> Result<(), OAuthStoreError> {
    let bytes = serde_json::to_vec(value)
        .map_err(|e| OAuthStoreError::Malformed(format!("encode JSON: {e}")))?;
    bucket.hash_set(key, "data", bytes)?;
    Ok(())
}

fn read_json_hash<T: serde::de::DeserializeOwned>(
    bucket: &mut Bucket,
    key: &str,
) -> Result<Option<T>, OAuthStoreError> {
    let Some(bytes) = bucket.hash_get(key, "data")? else {
        return Ok(None);
    };
    let value = serde_json::from_slice(&bytes)
        .map_err(|e| OAuthStoreError::Malformed(format!("decode JSON: {e}")))?;
    Ok(Some(value))
}

// -- Token-generation helpers -------------------------------------------------

/// Generate a `wmc_<random>` client id. 16 random bytes encoded
/// url-safe-base64 — collision-safe for any realistic number of
/// registered clients.
pub fn generate_client_id() -> String {
    let mut bytes = [0u8; 16];
    rand::rng().fill_bytes(&mut bytes);
    format!("wmc_{}", B64URL.encode(bytes))
}

/// Generate a `wmcs_<random>` client secret. 32 random bytes —
/// strong enough to survive any brute-force attempt against the
/// argon2id-hashed form persisted in storage.
pub fn generate_client_secret() -> String {
    let mut bytes = [0u8; 32];
    rand::rng().fill_bytes(&mut bytes);
    format!("wmcs_{}", B64URL.encode(bytes))
}

/// Random 32-byte url-safe-base64 string. Used for auth codes and
/// internal-state nonces — neither needs a typing prefix.
pub fn generate_random_token() -> String {
    let mut bytes = [0u8; 32];
    rand::rng().fill_bytes(&mut bytes);
    B64URL.encode(bytes)
}

/// Generate a `wmm_<random>` access token. The plaintext is returned
/// to the client exactly once; storage holds only the SHA-256 hash.
pub fn generate_access_token() -> String {
    let mut bytes = [0u8; 32];
    rand::rng().fill_bytes(&mut bytes);
    format!("wmm_{}", B64URL.encode(bytes))
}

/// Generate a `wmr_<random>` refresh token. Longer than the access
/// token (48 bytes) since it's directly exchangeable for new access
/// tokens — collision/guess resistance matters more.
pub fn generate_refresh_token() -> String {
    let mut bytes = [0u8; 48];
    rand::rng().fill_bytes(&mut bytes);
    format!("wmr_{}", B64URL.encode(bytes))
}

pub fn hash_token(plaintext: &str) -> String {
    let mut h = Sha256::new();
    h.update(plaintext.as_bytes());
    hex::encode(h.finalize())
}

/// Verify a PKCE code_verifier against a stored code_challenge. v1
/// only accepts S256 (matching the discovery advertisement); `plain`
/// is rejected at request parse time. Compares with constant-time
/// equality so a slow attacker can't time-attack the challenge.
fn verify_pkce(challenge: &str, verifier: &str) -> bool {
    use subtle::ConstantTimeEq;
    let mut h = Sha256::new();
    h.update(verifier.as_bytes());
    let computed = B64URL.encode(h.finalize());
    computed.as_bytes().ct_eq(challenge.as_bytes()).into()
}

// -- Redirect-URI validation --------------------------------------------------

/// Whether `provided` matches any of `registered` under RFC 8252
/// rules: exact match, EXCEPT loopback addresses (`http://127.0.0.1`
/// and `http://[::1]`) match registered loopback URIs ignoring the
/// port. Required because native MCP clients bind a random local
/// port per session.
fn redirect_uri_matches(registered: &[String], provided: &str) -> bool {
    for reg in registered {
        if reg == provided {
            return true;
        }
        if let (Some(reg_lb), Some(prov_lb)) =
            (loopback_normalize(reg), loopback_normalize(provided))
            && reg_lb == prov_lb
        {
            return true;
        }
    }
    false
}

/// Strip the port from a loopback URI (`http://127.0.0.1:1234/cb` →
/// `Some("http://127.0.0.1/cb")`). Returns `None` for any URI that
/// isn't loopback; non-loopback URIs only match on exact equality.
fn loopback_normalize(uri: &str) -> Option<String> {
    let parsed = reqwest::Url::parse(uri).ok()?;
    if parsed.scheme() != "http" {
        return None;
    }
    let host = parsed.host_str()?;
    if host != "127.0.0.1" && host != "[::1]" && host != "::1" {
        return None;
    }
    let path = parsed.path();
    Some(format!("http://{host}{path}"))
}

// -- DCR: POST /__auth/oauth/register -----------------------------------------

#[derive(Debug, Deserialize)]
struct RegisterBody {
    client_name: Option<String>,
    redirect_uris: Vec<String>,
    grant_types: Option<Vec<String>>,
    response_types: Option<Vec<String>>,
    token_endpoint_auth_method: Option<String>,
}

#[derive(Debug, Serialize)]
struct RegisterResponse {
    client_id: String,
    client_secret: String,
    client_name: String,
    redirect_uris: Vec<String>,
    grant_types: Vec<String>,
    response_types: Vec<String>,
    token_endpoint_auth_method: String,
    client_id_issued_at: i64,
}

async fn register(State(state): State<AppState>, Json(body): Json<RegisterBody>) -> Response {
    if body.redirect_uris.is_empty() {
        return oauth_error(
            StatusCode::BAD_REQUEST,
            "invalid_redirect_uri",
            "at least one redirect_uri is required",
        );
    }
    for uri in &body.redirect_uris {
        if let Err(msg) = validate_redirect_uri_at_registration(uri) {
            return oauth_error(StatusCode::BAD_REQUEST, "invalid_redirect_uri", &msg);
        }
    }

    let client_id = generate_client_id();
    let plaintext_secret = generate_client_secret();
    // Reuse the argon2id config from local_auth so registered-client
    // secrets get the same strength treatment as user passwords.
    let secret_hash = match crate::local_auth::hash_password(&plaintext_secret) {
        Ok(h) => h,
        Err(e) => {
            tracing::error!(error = %e, "hash client secret");
            return oauth_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                "server_error",
                "internal error hashing secret",
            );
        }
    };

    let grant_types = body
        .grant_types
        .unwrap_or_else(|| vec!["authorization_code".into(), "refresh_token".into()]);
    let response_types = body.response_types.unwrap_or_else(|| vec!["code".into()]);
    let token_endpoint_auth_method = body
        .token_endpoint_auth_method
        .unwrap_or_else(|| "client_secret_post".into());

    let client = OAuthClient {
        client_id: client_id.clone(),
        client_secret_hash: secret_hash,
        client_name: body.client_name.unwrap_or_else(|| "Unnamed Client".into()),
        redirect_uris: body.redirect_uris.clone(),
        grant_types: grant_types.clone(),
        response_types: response_types.clone(),
        token_endpoint_auth_method: token_endpoint_auth_method.clone(),
        created_at: Utc::now(),
        last_used_at: None,
        revoked_at: None,
    };

    let mut bucket = match state.auth().storage().admin_bucket() {
        Ok(b) => b,
        Err(e) => {
            tracing::error!(error = %e, "open admin bucket");
            return oauth_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                "server_error",
                "internal error",
            );
        }
    };
    if let Err(e) = save_client(&mut bucket, &client) {
        tracing::error!(error = %e, "save oauth client");
        return oauth_error(
            StatusCode::INTERNAL_SERVER_ERROR,
            "server_error",
            "internal error",
        );
    }

    let resp = RegisterResponse {
        client_id,
        client_secret: plaintext_secret,
        client_name: client.client_name,
        redirect_uris: client.redirect_uris,
        grant_types,
        response_types,
        token_endpoint_auth_method,
        client_id_issued_at: client.created_at.timestamp(),
    };
    (StatusCode::CREATED, Json(resp)).into_response()
}

fn validate_redirect_uri_at_registration(uri: &str) -> Result<(), String> {
    let parsed = reqwest::Url::parse(uri).map_err(|e| format!("malformed URI {uri:?}: {e}"))?;
    match parsed.scheme() {
        "https" => Ok(()),
        "http" => {
            // Allow http only for loopback addresses (RFC 8252).
            let host = parsed.host_str().unwrap_or("");
            if host == "127.0.0.1" || host == "[::1]" || host == "::1" || host == "localhost" {
                Ok(())
            } else {
                Err(format!(
                    "http redirect_uri must be loopback (127.0.0.1, [::1], or localhost), got {uri:?}"
                ))
            }
        }
        other => Err(format!(
            "redirect_uri scheme must be http (loopback) or https, got {other:?}"
        )),
    }
}

// -- Authorize: GET /__auth/oauth/authorize -----------------------------------

#[derive(Debug, Deserialize)]
struct AuthorizeQuery {
    response_type: Option<String>,
    client_id: Option<String>,
    redirect_uri: Option<String>,
    state: Option<String>,
    scope: Option<String>,
    code_challenge: Option<String>,
    code_challenge_method: Option<String>,
}

async fn authorize(
    State(state): State<AppState>,
    headers: HeaderMap,
    Query(q): Query<AuthorizeQuery>,
    raw_uri: axum::http::Uri,
) -> Response {
    // Parameter validation — anything client-facing returns a
    // structured `?error=...` redirect to the registered URI; pre-
    // client-lookup failures return a plain 400 so the user can see
    // the message.
    let response_type = match q.response_type.as_deref() {
        Some("code") => "code",
        _ => {
            return (
                StatusCode::BAD_REQUEST,
                "missing or unsupported response_type (must be \"code\")",
            )
                .into_response();
        }
    };
    let Some(client_id) = q.client_id else {
        return (StatusCode::BAD_REQUEST, "missing client_id").into_response();
    };
    let Some(redirect_uri) = q.redirect_uri else {
        return (StatusCode::BAD_REQUEST, "missing redirect_uri").into_response();
    };
    let Some(code_challenge) = q.code_challenge else {
        return (
            StatusCode::BAD_REQUEST,
            "PKCE code_challenge is required (S256 only)",
        )
            .into_response();
    };
    let code_challenge_method = q.code_challenge_method.as_deref().unwrap_or("S256");
    if code_challenge_method != "S256" {
        return (
            StatusCode::BAD_REQUEST,
            "code_challenge_method must be S256",
        )
            .into_response();
    }

    let mut bucket = match state.auth().storage().admin_bucket() {
        Ok(b) => b,
        Err(e) => {
            tracing::error!(error = %e, "open admin bucket");
            return (StatusCode::INTERNAL_SERVER_ERROR, "internal error").into_response();
        }
    };
    let client = match load_client(&mut bucket, &client_id) {
        Ok(Some(c)) if c.revoked_at.is_none() => c,
        Ok(Some(_)) => {
            return (StatusCode::UNAUTHORIZED, "client is revoked").into_response();
        }
        Ok(None) => {
            return (StatusCode::UNAUTHORIZED, "unknown client_id").into_response();
        }
        Err(e) => {
            tracing::error!(error = %e, "load oauth client");
            return (StatusCode::INTERNAL_SERVER_ERROR, "internal error").into_response();
        }
    };

    if !redirect_uri_matches(&client.redirect_uris, &redirect_uri) {
        return (
            StatusCode::BAD_REQUEST,
            "redirect_uri does not match any registered URI",
        )
            .into_response();
    }

    if response_type != "code" {
        return (StatusCode::BAD_REQUEST, "internal: response_type drift").into_response();
    }

    // Session check. Without a logged-in UI user we can't bind the
    // pending authorization to anyone, so we punt to the login page
    // and resume after.
    if !session_is_valid(&state, &headers) {
        let next = raw_uri.path_and_query().map(|pq| pq.as_str()).unwrap_or("");
        let login_url = format!("/__auth/login?next={}", percent_encode(next));
        return Redirect::to(&login_url).into_response();
    }

    // Stash a pending authorization keyed by an internal nonce and
    // hand the user off to the consent page. The nonce is what we
    // pass through the consent UI — the client's original `state`
    // lives inside the pending record and only comes back out when
    // we redirect to the client's redirect_uri.
    let internal_state = generate_random_token();
    let pending = PendingAuthorization {
        client_id: client.client_id.clone(),
        redirect_uri,
        code_challenge,
        code_challenge_method: code_challenge_method.into(),
        scope: q.scope.unwrap_or_else(|| "*".into()),
        original_state: q.state,
        created_at: Utc::now(),
    };
    if let Err(e) = save_pending(&mut bucket, &internal_state, &pending) {
        tracing::error!(error = %e, "save pending oauth");
        return (StatusCode::INTERNAL_SERVER_ERROR, "internal error").into_response();
    }

    let target = format!(
        "/__ui/oauth/consent?state={state}",
        state = percent_encode(&internal_state)
    );
    Redirect::to(&target).into_response()
}

/// Percent-encode for embedding into a query parameter. Keeps the
/// query-safe alphabet untouched; everything else gets `%XX`.
fn percent_encode(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for b in s.as_bytes() {
        match *b {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' | b'/' => {
                out.push(*b as char);
            }
            _ => out.push_str(&format!("%{:02X}", b)),
        }
    }
    out
}

fn session_is_valid(state: &AppState, headers: &HeaderMap) -> bool {
    let Some(sessions) = state.sessions() else {
        return false;
    };
    let Some(cookie) = pick_session_cookie(headers) else {
        return false;
    };
    sessions.touch(&cookie).is_ok()
}

fn pick_session_cookie(headers: &HeaderMap) -> Option<String> {
    for value in headers.get_all(header::COOKIE).iter() {
        let Ok(raw) = value.to_str() else { continue };
        for pair in raw.split(';') {
            let pair = pair.trim();
            if let Some(v) = pair.strip_prefix(&format!("{}=", crate::session::COOKIE_NAME)) {
                return Some(v.to_string());
            }
        }
    }
    None
}

fn resolve_session_user(state: &AppState, headers: &HeaderMap) -> Option<String> {
    let sessions = state.sessions()?;
    let cookie = pick_session_cookie(headers)?;
    let session = sessions.touch(&cookie).ok()?;
    Some(session.user_id)
}

// -- Consent: GET/POST /__ui/oauth/consent -----------------------------------

#[derive(Debug, Deserialize)]
struct ConsentQuery {
    state: Option<String>,
}

async fn consent_page(
    State(state): State<AppState>,
    headers: HeaderMap,
    Query(q): Query<ConsentQuery>,
) -> Response {
    if !session_is_valid(&state, &headers) {
        return Redirect::to("/__auth/login?next=/__ui/").into_response();
    }
    let Some(internal_state) = q.state else {
        return (StatusCode::BAD_REQUEST, "missing state").into_response();
    };
    // Read (don't consume) — consent_submit consumes it on approve.
    let mut bucket = match state.auth().storage().admin_bucket() {
        Ok(b) => b,
        Err(e) => {
            tracing::error!(error = %e, "open bucket");
            return (StatusCode::INTERNAL_SERVER_ERROR, "internal error").into_response();
        }
    };
    let pending: Option<PendingAuthorization> =
        match read_json_hash(&mut bucket, &pending_key(&internal_state)) {
            Ok(p) => p,
            Err(e) => {
                tracing::error!(error = %e, "read pending");
                return (StatusCode::INTERNAL_SERVER_ERROR, "internal error").into_response();
            }
        };
    let Some(pending) = pending else {
        return (
            StatusCode::BAD_REQUEST,
            "consent request expired or already handled — restart the login flow from your MCP client",
        )
            .into_response();
    };
    let client_name = load_client(&mut bucket, &pending.client_id)
        .ok()
        .flatten()
        .map(|c| c.client_name)
        .unwrap_or_else(|| "Unknown client".into());

    crate::ui::render(
        &state,
        "oauth_consent.html",
        context! {
            state => internal_state,
            client_name => client_name,
            scope => pending.scope,
            redirect_uri => pending.redirect_uri,
        },
    )
}

#[derive(Debug, Deserialize)]
struct ConsentForm {
    state: String,
    action: String,
    #[serde(rename = "_csrf")]
    _csrf: Option<String>,
}

async fn consent_submit(
    State(state): State<AppState>,
    headers: HeaderMap,
    Form(form): Form<ConsentForm>,
) -> Response {
    let Some(user_id) = resolve_session_user(&state, &headers) else {
        return Redirect::to("/__auth/login?next=/__ui/").into_response();
    };
    let mut bucket = match state.auth().storage().admin_bucket() {
        Ok(b) => b,
        Err(e) => {
            tracing::error!(error = %e, "open bucket");
            return (StatusCode::INTERNAL_SERVER_ERROR, "internal error").into_response();
        }
    };
    let pending = match consume_pending(&mut bucket, &form.state) {
        Ok(Some(p)) => p,
        Ok(None) => {
            return (
                StatusCode::BAD_REQUEST,
                "consent request expired or already handled",
            )
                .into_response();
        }
        Err(e) => {
            tracing::error!(error = %e, "consume pending");
            return (StatusCode::INTERNAL_SERVER_ERROR, "internal error").into_response();
        }
    };

    let original_state = pending.original_state.clone().unwrap_or_default();

    if form.action == "deny" {
        let url = build_redirect_with_params(
            &pending.redirect_uri,
            &[
                ("error", "access_denied"),
                ("error_description", "user denied the authorization request"),
                ("state", &original_state),
            ],
        );
        return Redirect::to(&url).into_response();
    }
    if form.action != "approve" {
        return (StatusCode::BAD_REQUEST, "invalid action").into_response();
    }

    // Approve: mint an authorization code and redirect to the
    // client's redirect_uri carrying it.
    let code_plaintext = generate_random_token();
    let code_record = AuthorizationCode {
        code: code_plaintext.clone(),
        client_id: pending.client_id.clone(),
        user_id,
        redirect_uri: pending.redirect_uri.clone(),
        scope: pending.scope.clone(),
        code_challenge: pending.code_challenge.clone(),
        code_challenge_method: pending.code_challenge_method.clone(),
        created_at: Utc::now(),
        used_at: None,
    };
    if let Err(e) = save_authorization_code(&mut bucket, &code_record) {
        tracing::error!(error = %e, "save auth code");
        return (StatusCode::INTERNAL_SERVER_ERROR, "internal error").into_response();
    }

    let url = build_redirect_with_params(
        &pending.redirect_uri,
        &[("code", &code_plaintext), ("state", &original_state)],
    );
    Redirect::to(&url).into_response()
}

fn build_redirect_with_params(base: &str, params: &[(&str, &str)]) -> String {
    let mut url = match reqwest::Url::parse(base) {
        Ok(u) => u,
        Err(_) => return base.to_string(),
    };
    {
        let mut q = url.query_pairs_mut();
        for (k, v) in params {
            if !v.is_empty() {
                q.append_pair(k, v);
            }
        }
    }
    url.into()
}

// -- Token: POST /__auth/oauth/token ------------------------------------------

#[derive(Debug, Deserialize)]
struct TokenForm {
    grant_type: String,
    // authorization_code grant fields
    code: Option<String>,
    redirect_uri: Option<String>,
    code_verifier: Option<String>,
    // refresh_token grant fields. Parsed but not yet consumed in
    // slice 52 — the refresh handler lands in slice 53. Keeping the
    // field declared so serde doesn't drop it when clients start
    // sending it ahead of that handler being wired.
    #[allow(dead_code)]
    refresh_token: Option<String>,
    // client auth via client_secret_post (form fields)
    client_id: Option<String>,
    client_secret: Option<String>,
}

#[derive(Debug, Serialize)]
struct TokenResponse {
    access_token: String,
    token_type: String,
    expires_in: u64,
    scope: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    refresh_token: Option<String>,
}

async fn token(
    State(state): State<AppState>,
    headers: HeaderMap,
    Form(form): Form<TokenForm>,
) -> Response {
    let mut bucket = match state.auth().storage().admin_bucket() {
        Ok(b) => b,
        Err(e) => {
            tracing::error!(error = %e, "open bucket");
            return oauth_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                "server_error",
                "internal error",
            );
        }
    };

    // Resolve client auth. RFC 6749 §2.3.1 says clients SHOULD use
    // HTTP Basic; some libraries default to form-post. We accept
    // both: Authorization: Basic ..., then client_id+client_secret
    // form fields as fallback.
    let client_auth = match extract_client_auth(&headers, &form) {
        Some(a) => a,
        None => {
            return oauth_error(
                StatusCode::UNAUTHORIZED,
                "invalid_client",
                "missing client credentials",
            );
        }
    };

    let client = match load_client(&mut bucket, &client_auth.client_id) {
        Ok(Some(c)) if c.revoked_at.is_none() => c,
        _ => {
            return oauth_error(
                StatusCode::UNAUTHORIZED,
                "invalid_client",
                "unknown or revoked client",
            );
        }
    };
    if !crate::local_auth::verify_password(&client.client_secret_hash, &client_auth.client_secret) {
        return oauth_error(
            StatusCode::UNAUTHORIZED,
            "invalid_client",
            "client authentication failed",
        );
    }

    match form.grant_type.as_str() {
        "authorization_code" => {
            handle_authorization_code_grant(&mut bucket, &client, &form, &state).await
        }
        "refresh_token" => handle_refresh_token_grant(&mut bucket, &client, &form).await,
        other => oauth_error(
            StatusCode::BAD_REQUEST,
            "unsupported_grant_type",
            &format!("unsupported grant_type {other:?}"),
        ),
    }
}

struct ClientAuth {
    client_id: String,
    client_secret: String,
}

fn extract_client_auth(headers: &HeaderMap, form: &TokenForm) -> Option<ClientAuth> {
    if let Some(v) = headers.get(header::AUTHORIZATION)
        && let Ok(raw) = v.to_str()
        && let Some(b64) = raw.strip_prefix("Basic ")
    {
        let bytes = B64URL
            .decode(b64)
            .or_else(|_| base64::engine::general_purpose::STANDARD.decode(b64));
        if let Ok(decoded) = bytes
            && let Ok(text) = String::from_utf8(decoded)
            && let Some((id, secret)) = text.split_once(':')
        {
            return Some(ClientAuth {
                client_id: id.to_string(),
                client_secret: secret.to_string(),
            });
        }
    }
    if let (Some(id), Some(secret)) = (form.client_id.as_deref(), form.client_secret.as_deref()) {
        return Some(ClientAuth {
            client_id: id.to_string(),
            client_secret: secret.to_string(),
        });
    }
    None
}

async fn handle_authorization_code_grant(
    bucket: &mut Bucket,
    client: &OAuthClient,
    form: &TokenForm,
    state: &AppState,
) -> Response {
    let _ = state; // session/auth touches happen via store directly
    let Some(code) = form.code.as_deref() else {
        return oauth_error(StatusCode::BAD_REQUEST, "invalid_request", "missing `code`");
    };
    let Some(redirect_uri) = form.redirect_uri.as_deref() else {
        return oauth_error(
            StatusCode::BAD_REQUEST,
            "invalid_request",
            "missing `redirect_uri`",
        );
    };
    let Some(verifier) = form.code_verifier.as_deref() else {
        return oauth_error(
            StatusCode::BAD_REQUEST,
            "invalid_request",
            "missing PKCE `code_verifier`",
        );
    };

    let consumed = match consume_authorization_code(bucket, code) {
        Ok(Some(c)) => c,
        Ok(None) => {
            // Missing OR replayed — `consume_*` collapses both into
            // None so handlers can't accidentally accept a replay.
            return oauth_error(
                StatusCode::BAD_REQUEST,
                "invalid_grant",
                "authorization code not found, already used, or expired",
            );
        }
        Err(e) => {
            tracing::error!(error = %e, "consume auth code");
            return oauth_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                "server_error",
                "internal error",
            );
        }
    };
    if consumed.client_id != client.client_id {
        return oauth_error(
            StatusCode::BAD_REQUEST,
            "invalid_grant",
            "code does not belong to this client",
        );
    }
    if consumed.redirect_uri != redirect_uri {
        return oauth_error(
            StatusCode::BAD_REQUEST,
            "invalid_grant",
            "redirect_uri does not match the code's binding",
        );
    }
    if !verify_pkce(&consumed.code_challenge, verifier) {
        return oauth_error(
            StatusCode::BAD_REQUEST,
            "invalid_grant",
            "PKCE verifier does not match challenge",
        );
    }

    // Mint access token + refresh token. Refresh token lives in
    // slice 53; for now we issue it but the only way to use it is
    // via the same authorization_code flow, which is fine.
    let access_plaintext = generate_access_token();
    let access_hash = hash_token(&access_plaintext);
    let now = Utc::now();
    let expires_at = now + chrono::Duration::seconds(ACCESS_TOKEN_TTL_SECONDS as i64);
    let access_record = AccessToken {
        token_hash: access_hash,
        client_id: client.client_id.clone(),
        user_id: consumed.user_id.clone(),
        scope: consumed.scope.clone(),
        created_at: now,
        expires_at,
    };
    if let Err(e) = save_access_token(bucket, &access_record) {
        tracing::error!(error = %e, "save access token");
        return oauth_error(
            StatusCode::INTERNAL_SERVER_ERROR,
            "server_error",
            "internal error",
        );
    }

    let refresh_plaintext = generate_refresh_token();
    let refresh_hash = hash_token(&refresh_plaintext);
    let refresh_record = RefreshToken {
        token_hash: refresh_hash,
        client_id: client.client_id.clone(),
        user_id: consumed.user_id.clone(),
        scope: consumed.scope.clone(),
        created_at: now,
        used_at: None,
        revoked_at: None,
    };
    if let Err(e) = save_refresh_token(bucket, &refresh_record) {
        tracing::error!(error = %e, "save refresh token");
        return oauth_error(
            StatusCode::INTERNAL_SERVER_ERROR,
            "server_error",
            "internal error",
        );
    }

    let resp = TokenResponse {
        access_token: access_plaintext,
        token_type: "Bearer".into(),
        expires_in: ACCESS_TOKEN_TTL_SECONDS,
        scope: consumed.scope,
        refresh_token: Some(refresh_plaintext),
    };
    let mut response = Json(resp).into_response();
    response.headers_mut().insert(
        header::CACHE_CONTROL,
        axum::http::HeaderValue::from_static("no-store"),
    );
    response
}

async fn handle_refresh_token_grant(
    bucket: &mut Bucket,
    client: &OAuthClient,
    form: &TokenForm,
) -> Response {
    let Some(refresh_plaintext) = form.refresh_token.as_deref() else {
        return oauth_error(
            StatusCode::BAD_REQUEST,
            "invalid_request",
            "missing `refresh_token`",
        );
    };

    let hash = hash_token(refresh_plaintext);
    let consumed = match consume_refresh_token(bucket, &hash) {
        Ok(Some(r)) => r,
        Ok(None) => {
            // Missing OR replayed OR revoked — same shape as the
            // auth-code path.
            return oauth_error(
                StatusCode::BAD_REQUEST,
                "invalid_grant",
                "refresh token not found, already used, revoked, or expired",
            );
        }
        Err(e) => {
            tracing::error!(error = %e, "consume refresh token");
            return oauth_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                "server_error",
                "internal error",
            );
        }
    };
    if consumed.client_id != client.client_id {
        return oauth_error(
            StatusCode::BAD_REQUEST,
            "invalid_grant",
            "refresh token does not belong to this client",
        );
    }

    // Mint the new pair: access + (rotated) refresh.
    let access_plaintext = generate_access_token();
    let access_hash = hash_token(&access_plaintext);
    let now = Utc::now();
    let expires_at = now + chrono::Duration::seconds(ACCESS_TOKEN_TTL_SECONDS as i64);
    let access_record = AccessToken {
        token_hash: access_hash,
        client_id: consumed.client_id.clone(),
        user_id: consumed.user_id.clone(),
        scope: consumed.scope.clone(),
        created_at: now,
        expires_at,
    };
    if let Err(e) = save_access_token(bucket, &access_record) {
        tracing::error!(error = %e, "save access token (refresh path)");
        return oauth_error(
            StatusCode::INTERNAL_SERVER_ERROR,
            "server_error",
            "internal error",
        );
    }

    let new_refresh_plaintext = generate_refresh_token();
    let new_refresh_hash = hash_token(&new_refresh_plaintext);
    let new_refresh_record = RefreshToken {
        token_hash: new_refresh_hash,
        client_id: consumed.client_id.clone(),
        user_id: consumed.user_id.clone(),
        scope: consumed.scope.clone(),
        created_at: now,
        used_at: None,
        revoked_at: None,
    };
    if let Err(e) = save_refresh_token(bucket, &new_refresh_record) {
        tracing::error!(error = %e, "save refresh token (rotation)");
        return oauth_error(
            StatusCode::INTERNAL_SERVER_ERROR,
            "server_error",
            "internal error",
        );
    }

    let resp = TokenResponse {
        access_token: access_plaintext,
        token_type: "Bearer".into(),
        expires_in: ACCESS_TOKEN_TTL_SECONDS,
        scope: consumed.scope,
        refresh_token: Some(new_refresh_plaintext),
    };
    let mut response = Json(resp).into_response();
    response.headers_mut().insert(
        header::CACHE_CONTROL,
        axum::http::HeaderValue::from_static("no-store"),
    );
    response
}

// -- Revoke: POST /__auth/oauth/revoke ----------------------------------------

#[derive(Debug, Deserialize)]
struct RevokeForm {
    token: String,
    /// Optional hint at the token type — `access_token` or
    /// `refresh_token`. Per RFC 7009 we MAY ignore it (the spec is
    /// explicit that servers must look in both stores). We use it as
    /// a fast-path probe but always fall through to checking the
    /// other family if the hint misses.
    #[allow(dead_code)]
    token_type_hint: Option<String>,
    // Client auth via form fields (Basic header also accepted).
    client_id: Option<String>,
    client_secret: Option<String>,
}

async fn revoke(
    State(state): State<AppState>,
    headers: HeaderMap,
    Form(form): Form<RevokeForm>,
) -> Response {
    let mut bucket = match state.auth().storage().admin_bucket() {
        Ok(b) => b,
        Err(e) => {
            tracing::error!(error = %e, "open bucket");
            return oauth_error(
                StatusCode::INTERNAL_SERVER_ERROR,
                "server_error",
                "internal error",
            );
        }
    };

    let tok_form = TokenForm {
        grant_type: "_revoke_".into(),
        code: None,
        redirect_uri: None,
        code_verifier: None,
        refresh_token: None,
        client_id: form.client_id.clone(),
        client_secret: form.client_secret.clone(),
    };
    let Some(client_auth) = extract_client_auth(&headers, &tok_form) else {
        return oauth_error(
            StatusCode::UNAUTHORIZED,
            "invalid_client",
            "missing client credentials",
        );
    };
    let client = match load_client(&mut bucket, &client_auth.client_id) {
        Ok(Some(c)) if c.revoked_at.is_none() => c,
        _ => {
            return oauth_error(
                StatusCode::UNAUTHORIZED,
                "invalid_client",
                "unknown or revoked client",
            );
        }
    };
    if !crate::local_auth::verify_password(&client.client_secret_hash, &client_auth.client_secret) {
        return oauth_error(
            StatusCode::UNAUTHORIZED,
            "invalid_client",
            "client authentication failed",
        );
    }

    let hash = hash_token(&form.token);

    // Try access-token store first — most common revoke shape.
    if let Ok(Some(access)) = load_access_token(&mut bucket, &hash) {
        if access.client_id == client.client_id {
            let _ = delete_access_token(&mut bucket, &hash);
        }
        // Per RFC 7009: always 200 to prevent token enumeration.
        return StatusCode::OK.into_response();
    }

    // Refresh tokens: mark revoked so any in-flight rotation fails.
    if let Ok(Some(mut refresh)) = load_refresh_token(&mut bucket, &hash)
        && refresh.client_id == client.client_id
        && refresh.revoked_at.is_none()
    {
        refresh.revoked_at = Some(Utc::now());
        let _ = save_refresh_token(&mut bucket, &refresh);
    }
    // Unknown / mismatched-client tokens also return 200 by design.
    StatusCode::OK.into_response()
}

// -- Error response shape ----------------------------------------------------

fn oauth_error(status: StatusCode, code: &str, description: &str) -> Response {
    let body: HashMap<&str, &str> = [("error", code), ("error_description", description)]
        .into_iter()
        .collect();
    (status, Json(body)).into_response()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::store::Storage;

    fn fresh_bucket() -> Bucket {
        Storage::in_memory().admin_bucket().expect("bucket")
    }

    fn sample_client() -> OAuthClient {
        OAuthClient {
            client_id: "cli_abc".into(),
            client_secret_hash: "argon2id$...".into(),
            client_name: "Claude Desktop".into(),
            redirect_uris: vec!["http://127.0.0.1:0/callback".into()],
            grant_types: vec!["authorization_code".into(), "refresh_token".into()],
            response_types: vec!["code".into()],
            token_endpoint_auth_method: "client_secret_post".into(),
            created_at: Utc::now(),
            last_used_at: None,
            revoked_at: None,
        }
    }

    #[test]
    fn client_round_trips_through_storage() {
        let mut b = fresh_bucket();
        let c = sample_client();
        save_client(&mut b, &c).unwrap();
        let loaded = load_client(&mut b, &c.client_id).unwrap().unwrap();
        assert_eq!(loaded, c);
    }

    #[test]
    fn load_client_missing_returns_none() {
        let mut b = fresh_bucket();
        assert!(load_client(&mut b, "nope").unwrap().is_none());
    }

    #[test]
    fn revoke_client_marks_revoked_at() {
        let mut b = fresh_bucket();
        let c = sample_client();
        save_client(&mut b, &c).unwrap();
        assert!(revoke_client(&mut b, &c.client_id).unwrap());
        let loaded = load_client(&mut b, &c.client_id).unwrap().unwrap();
        assert!(loaded.revoked_at.is_some());
        // Already-revoked: second call is a no-op (returns false).
        assert!(!revoke_client(&mut b, &c.client_id).unwrap());
    }

    #[test]
    fn revoke_client_unknown_returns_false() {
        let mut b = fresh_bucket();
        assert!(!revoke_client(&mut b, "nope").unwrap());
    }

    #[test]
    fn pending_authorization_round_trip_and_consume() {
        let mut b = fresh_bucket();
        let p = PendingAuthorization {
            client_id: "cli_abc".into(),
            redirect_uri: "http://127.0.0.1:0/cb".into(),
            code_challenge: "challenge".into(),
            code_challenge_method: "S256".into(),
            scope: "*".into(),
            original_state: Some("client-state-xyz".into()),
            created_at: Utc::now(),
        };
        save_pending(&mut b, "internal-state", &p).unwrap();

        // First consume returns the record and deletes it.
        let first = consume_pending(&mut b, "internal-state").unwrap();
        assert_eq!(first, Some(p));
        // Second consume returns None.
        assert!(consume_pending(&mut b, "internal-state").unwrap().is_none());
    }

    #[test]
    fn authorization_code_consume_is_one_shot() {
        let mut b = fresh_bucket();
        let c = AuthorizationCode {
            code: "code_xyz".into(),
            client_id: "cli_abc".into(),
            user_id: "01HUSER".into(),
            redirect_uri: "http://127.0.0.1:0/cb".into(),
            scope: "*".into(),
            code_challenge: "ch".into(),
            code_challenge_method: "S256".into(),
            created_at: Utc::now(),
            used_at: None,
        };
        save_authorization_code(&mut b, &c).unwrap();

        // First consume marks used_at and returns the (now-marked) record.
        let first = consume_authorization_code(&mut b, "code_xyz")
            .unwrap()
            .unwrap();
        assert!(first.used_at.is_some());

        // Second consume returns None — replay protection. Missing
        // codes also return None; the token endpoint maps either to
        // `invalid_grant`, so collapsing them here keeps handler
        // logic simple and replay-safe.
        assert!(
            consume_authorization_code(&mut b, "code_xyz")
                .unwrap()
                .is_none()
        );

        // The record itself sticks around (with used_at set) so
        // diagnostic queries can still see "this code WAS used."
        let still_there: Option<AuthorizationCode> =
            read_json_hash(&mut b, &code_key("code_xyz")).unwrap();
        assert!(still_there.unwrap().used_at.is_some());

        // Truly missing → None.
        assert!(
            consume_authorization_code(&mut b, "nope")
                .unwrap()
                .is_none()
        );
    }

    #[test]
    fn refresh_token_rotation_blocks_replay() {
        let mut b = fresh_bucket();
        let t = RefreshToken {
            token_hash: "hash1".into(),
            client_id: "cli_abc".into(),
            user_id: "01HUSER".into(),
            scope: "*".into(),
            created_at: Utc::now(),
            used_at: None,
            revoked_at: None,
        };
        save_refresh_token(&mut b, &t).unwrap();

        let first = consume_refresh_token(&mut b, "hash1").unwrap().unwrap();
        assert!(first.used_at.is_some());

        // Replay returns None.
        assert!(consume_refresh_token(&mut b, "hash1").unwrap().is_none());
    }

    #[test]
    fn refresh_token_revoked_is_treated_as_missing_by_consume() {
        let mut b = fresh_bucket();
        let t = RefreshToken {
            token_hash: "hash2".into(),
            client_id: "cli_abc".into(),
            user_id: "01HUSER".into(),
            scope: "*".into(),
            created_at: Utc::now(),
            used_at: None,
            revoked_at: Some(Utc::now()),
        };
        save_refresh_token(&mut b, &t).unwrap();
        // Revoked tokens look like replays to consume() — same shape
        // collapses both rejection cases.
        assert!(consume_refresh_token(&mut b, "hash2").unwrap().is_none());

        // The record stays around so diagnostic queries still see it.
        let still_there = load_refresh_token(&mut b, "hash2").unwrap().unwrap();
        assert!(still_there.revoked_at.is_some());
    }
}
